# Generated by Django 3.2.4 on 2021-06-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('date_printed', models.DateTimeField(blank=True, null=True, verbose_name='date printed')),
                ('printed_by', models.CharField(max_length=200)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.roll')),
            ],
        ),
    ]
