# Generated by Django 3.2.4 on 2021-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
