# Generated by Django 3.2.4 on 2021-06-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_roll_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='psk',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='portal',
            name='ssid',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
