# Generated by Django 3.2.4 on 2021-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20210607_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='voucher_csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='printed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
