# Generated by Django 3.2.4 on 2021-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('voucher', '0005_alter_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='allow_printing',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
