# Generated by Django 3.2.4 on 2021-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20210608_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
