# Generated by Django 3.2.4 on 2021-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('voucher', '0008_portal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='allow_printing',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
