# Generated by Django 3.2.4 on 2021-06-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_alter_voucher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={},
        ),
    ]
